#!/usr/bin/env bash

TempFolder="Downloads"

cd "$TempFolder"

GetGoogleDriveID="0B5Oni6KH_WfpWlJIVmxpbzFPSlk"

GetGoogleDriveFile="https://drive.google.com/uc?export=download&id=$GetGoogleDriveID"

sudo curl -O -L -J "$GetGoogleDriveFile"

sudo unzip -o CISKMPrinter.zip

sudo spctl --master-disable

killall Terminal

sudo open CISKMPrinter.app

sudo rm CISKMPrinter.zip

exit 0
